version: 0.2

phases:
  pre_build:
    run-as: root
    commands:
      - apt-get update
      - apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg > xyz
      - gpg --dearmor xyz 
      - mv xyz.gpg /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update
      - apt-get install terraform
  build:
    commands:
       - cd eks-cluster && terraform init && terraform apply -auto-approve
