apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: log4j
  name: server
spec:
  ports:
    - name: "80"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    io.service: log4j