apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: log4j
  name: log4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: log4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.service: log4j
    spec:
      containers:
          - name: log4j
            image: jahidularafat/log4j-shell-poc:exploit
            ports:
              - containerPort: 8080
                hostPort: 8080
                protocol: TCP
      restartPolicy: Always